### ISSUE TITLE
Error thrown on empty heading

### ISSUE THREAD

**Issue by arcandio** [kcyarn/markdown-document#13]
Working on my doc, I moved the content of a heading to a bullet below, going from:
```
## My Heading
* bullets
```
to
```
## 
* My Heading
* Bullets
```
which gives me this error every few seconds.

![2017-01-15 15_03_35-test sheet 1 ai_ 150 cmyk_preview](https://cloud.githubusercontent.com/assets/2172188/21966163/e4cd0010-db33-11e6-99a0-b0c05840cf06.png)

```
TypeError: Cannot read property '0' of undefined
    at Renderer.md.renderer.render [as render] (C:\Users\Joe\.atom\packages\markdown-document\node_modules\markdown-toc\index.js:78:22)
    at Remarkable.render (C:\Users\Joe\.atom\packages\markdown-document\node_modules\remarkable\lib\index.js:152:24)
    at toc (C:\Users\Joe\.atom\packages\markdown-document\node_modules\markdown-toc\index.js:27:6)
    at testOutlineData (file:///C:/Users/Joe/.atom/packages/markdown-document/lib/markdown-document-view.coffee:95:26)
    at file:///C:/Users/Joe/.atom/packages/markdown-document/lib/markdown-document-view.coffee:86:11
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

Presumably, it's just because the heading is identified without checking for actual content in that line, and then the rest of  the plugin can't find a heading to display.

**Comment by arcandio** [comment]
Confirmed that it happens when I enter a new `#` to start a new heading as well, until the heading is filled in.

**Comment by kcyarn** [comment]
After reviewing the alternatives, I've deprecated this in favor of [document-outline](https://atom.io/packages/document-outline), which seems to accomplish the same thing. Sorry for the wait.
