### ISSUE TITLE
Uncaught TypeError: this.refreshClick is not a function

### ISSUE THREAD

**Issue by tatoosh** [kcyarn/markdown-document#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: A2015011
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package 0.2.1

### Stack Trace

Uncaught TypeError: this.refreshClick is not a function

```
At C:\Users\atrabert\.atom\packages\markdown-document\lib\markdown-document-view.coffee:324

TypeError: this.refreshClick is not a function
    at MarkdownDocumentView.module.exports.MarkdownDocumentView.refreshOutline (/packages/markdown-document/lib/markdown-document-view.coffee:324:6)
    at Object.refresh (/packages/markdown-document/lib/markdown-document.coffee:47:27)
    at /packages/markdown-document/lib/markdown-document.coffee:30:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:45 markdown-document:toggle (input.hidden-input)
     -0:12.7.0 markdown-document:refresh (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.29.17 
custom-invisibles 0.1.2 
git-plus 7.3.3 
language-groovy 0.6.0 
language-jpl 0.1.0 
markdown-document 0.2.1 
markdown-folder 0.5.0 
markdown-image-assistant 0.1.8 
markdown-preview-plus 2.4.9 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
pdf-view 0.57.0 
```

**Comment by kcyarn** [comment]
After reviewing the alternatives, I've deprecated this in favor of [document-outline](https://atom.io/packages/document-outline), which seems to accomplish the same thing. Sorry for the wait.
