### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by airdata** [kcyarn/markdown-document#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.2
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package 0.2.1

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:303

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readFile (fs.js:303:11)
    at Object.fs.readFile (ELECTRON_ASAR.js:451:25)
    at mdContent (/packages/markdown-document/lib/markdown-document-view.coffee:82:12)
    at /packages/markdown-document/lib/markdown-document-view.coffee:295:15
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/app.asar/src/pane.js:435:19)
    at Pane.module.exports.Pane.activatePreviousItem (/app.asar/src/pane.js:400:21)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:585:16)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at Pane.module.exports.Pane.destroyActiveItem (/app.asar/src/pane.js:638:12)
    at Workspace.destroyActivePaneItem (/app.asar/src/workspace.js:868:33)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/app.asar/src/workspace.js:929:12)
    at /app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:36.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -2:36.7.0 editor:newline (input.hidden-input)
  2x -2:35.1.0 core:save (input.hidden-input)
  2x -2:33.2.0 markdown-preview:toggle (input.hidden-input)
     -2:14 core:cut (input.hidden-input)
  3x -2:11.6.0 core:backspace (input.hidden-input)
     -2:05.2.0 markdown-writer:insert-new-line (input.hidden-input)
     -2:05.2.0 editor:newline (input.hidden-input)
  2x -2:04.4.0 core:save (input.hidden-input)
  6x -2:03.1.0 markdown-preview:toggle (input.hidden-input)
     -1:22.6.0 markdown-writer:create-project-configs (div.markdown-preview.native-key-bindings)
     -1:13.4.0 markdown-preview:toggle (input.hidden-input)
     -0:31.1.0 markdown-writer:manage-post-tags (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:21.6.0 core:select-all (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.0 markdown-writer:manage-post-tags (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:04.5.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-mdtoc 0.8.3 
markclip 0.4.0 
markdown-document 0.2.1 
markdown-writer 2.6.4 
softcover 0.1.0 
tool-bar-markdown-writer 0.2.0 
```

**Comment by kcyarn** [comment]
After reviewing the alternatives, I've deprecated this in favor of [document-outline](https://atom.io/packages/document-outline), which seems to accomplish the same thing. Sorry for the wait.
