### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mliq** [kcyarn/markdown-document#3]
I really love this idea, was always hoping I could get it for years, does it require markdown-document grammar?

[Enter steps to reproduce below:]
1. Open any .md markdown file. (Using default Github Markdown format)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/mliquori/Dropbox/config/atom/packages/markdown-document/lib/markdown-document-view.coffee:105

TypeError: Cannot read property '0' of undefined
    at /Users/mliquori/Dropbox/config/atom/packages/markdown-document/lib/markdown-document-view.coffee:105:52
    at Array.forEach (native)
    at MarkdownDocumentView.mdOutline (/Users/mliquori/Dropbox/config/atom/packages/markdown-document/lib/markdown-document-view.coffee:85:19)
    at /Users/mliquori/Dropbox/config/atom/packages/markdown-document/lib/markdown-document-view.coffee:76:9
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Commands

```
     -0:50.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:47.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:47.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:43.2.0 markdown-document:toggle (atom-text-editor.editor.is-focused)
     -0:12 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -0:10.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:10.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:08.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:05.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:05.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  4x -0:03.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "path-hyperclick",
      "file-hyperclick",
      "navigation-history",
      "split-diff",
      "tree-view-autoresize",
      "symbol-gen",
      "semanticolor",
      "fonts",
      "pigments",
      "rnn-writer",
      "language-javascript-semantic",
      "language-javascript-jsx",
      "git-diff-details",
      "language-javascript-better",
      "webbox-color",
      "atom-beautify",
      "tree-view-git-branch",
      "tree-view-git-status",
      "save-session",
      "js-refactor",
      "refactor",
      "git-history",
      "unsaved-changes",
      "Tern",
      "language-markdown",
      "markdown-preview",
      "autocomplete-ctags",
      "atom-ctags",
      "ctags-status"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view-filter",
      "bookmarks",
      "merge-conflicts"
    ],
    "projectHome": "/Users/mliquori/Dropbox/tech/projects",
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-material-syntax, v0.4.6
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-modules, v1.5.1
block-travel, v1.0.4
change-case, v0.6.0
color-picker, v2.1.1
docblockr, v0.7.3
editorconfig, v1.4.1
file-icons, v1.7.14
goto-last-edit, v0.3.2
highlight-selected, v0.11.2
hyperclick, v0.0.36
hyperclick-markdown, v0.1.3
indent-guide-improved, v1.4.8
js-hyperclick, v1.4.2
language-babel, v2.27.1
language-diff, v0.4.0
last-cursor-position, v0.9.0
line-diff-details, v1.3.5
linter, v1.11.8
linter-eslint, v7.2.2
local-history, v3.3.0
markdown-assistant, v0.2.0
markdown-document, v0.1.0
markdown-mindmap, v0.2.4
markdown-preview-plus, v2.4.0
merge-conflicts, v1.4.4
minimap, v4.24.4
minimap-cursorline, v0.2.0
project-manager, v2.9.7
recent-files-fuzzy-finder, v0.2.4
remember-file-positions, v0.2.2
tree-view-filter, v0.4.1

# Dev
No dev packages
```

**Comment by kcyarn** [comment]
Since the error's on line 105 and not earlier, I suspect it's a dependency issue.

Can you go to  /Users/mliquori/Dropbox/config/atom/packages/markdown-document/node_modules/markdown-toc/package.json and scroll all the way down to the bottom of the file?

Do lines 116-117 read

```
  "_resolved": "https://github.com/kcyarn/markdown-toc/tarball/master",
  "_from": "https://github.com/kcyarn/markdown-toc/tarball/master"
```

If doesn't say this, cd into the packages/markdown-document directory and run apm install then check it again.

So far, I haven't managed to duplicate the error, but I'll keep trying.

**Comment by kcyarn** [comment]
Just realized I didn't answer your question...

It doesn't require language-markdown. using the source.gfm (default gfm markdown) works, but I haven't tested it with mixed markdown/html or anything beyond a simple list of headers with some lorem ipsum content.

**Comment by mliq** [comment]
I tested it with new .md file using default Github Markdown and just one # header, same crash.

**Comment by kcyarn** [comment]
I'm terribly sorry. I screwed up and forgot to push the single line change to the markdown-toc repository when I published the package. I've released a patch that I believe will fix the problem. Please update the package.

**Comment by kcyarn** [comment]
Forgot to mention that sometimes atom needs to be restarted after installing. I'm still trying to track down why...

**Comment by mliq** [comment]
Awesome! Looks to be working, thanks so much! (I didn't need to restart either, but I think a lot of extensions have that issue so I wouldn't worry about it much if I was you.)
