### ISSUE TITLE
Uncaught TypeError: activePane.getPath is not a function

### ISSUE THREAD

**Issue by jamezpolley** [kcyarn/markdown-document#5]
[Enter steps to reproduce below:]
1. Be in a pane with a markdown document
2. Change to the "tasks" pane from the imdone-atom package

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package, v0.1.1
### Stack Trace

Uncaught TypeError: activePane.getPath is not a function

```
At /Users/james/.atom/packages/markdown-document/lib/markdown-document-view.coffee:171

TypeError: activePane.getPath is not a function
    at /Users/james/.atom/packages/markdown-document/lib/markdown-document-view.coffee:171:33
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:431:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:19)
```
### Commands

```
     -8:30 core:save (atom-text-editor.editor.emacs-plus.is-focused)
     -8:27.4.0 pane:show-item-2 (atom-text-editor.editor.emacs-plus.is-focused)
  2x -8:07.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
     -0:14.3.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused)
     -0:06.4.0 core:move-left (atom-text-editor.editor.emacs-plus.is-focused)
     -0:02.6.0 core:save (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "ever-notedown",
      "foldingtext-markdown",
      "tidy-markdown",
      "atom-trello",
      "markdown-preview",
      "toggle-markdown-task",
      "language-gfm"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-fuzzy-grep, v0.13.0
autocomplete-python, v1.8.1
click-link, v1.0.0
emacs-plus, v0.11.0
fountain, v0.2.0
imdone-atom, v1.3.29
language-dot, v1.6.0
language-markdown, v0.14.1
language-restructuredtext, v0.16.0
linter-markdown, v1.5.2
markdown-document, v0.1.1
markdown-preview-plus, v2.4.0
markdown-preview-plus-opener, v0.2.0
markdown-writer, v2.3.4
package-sync, v1.1.0
python-tools, v0.6.7
rst-preview-pandoc, v0.1.12
tasks, v2.6.0

# Dev
No dev packages
```

**Comment by kcyarn** [comment]
Sorry I didn't see this sooner. I was out of town and am still playing catch up. 0.1.1 does not support multiple panes. The [devJson branch](https://github.com/kcyarn/markdown-document/tree/devJSON), scheduled release date 6/28 as 0.2, does support multiple panes and should resolve this issue.

I haven't tested with the imdone package as I use todo.txt files for lists. Please let me know if there's a conflict with the imdone package itself. Git-plus, for example, required its own exception.

**Comment by kcyarn** [comment]
An exception for imdone's task pane was needed.
