### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by diqidoq** [kcyarn/markdown-document#6]
[Enter steps to reproduce below:]
1. Install package
2. Click on Package from an open MarkDown document

**Atom Version**: 1.8.0
**System**: Debian GNU/Linux _"Stretch"_ Desktop: LXDE/Openbox
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package, v0.1.1
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:262

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readFile (fs.js:262:11)
    at Object.fs.readFile (ATOM_SHELL_ASAR.js:375:25)
    at MarkdownDocumentView.mdContent (/home/<user>/.atom/packages/markdown-document/lib/markdown-document-view.coffee:72:10)
    at MarkdownDocumentView.refreshClick.refreshClick [as refreshClick] (/home/<user>/.atom/packages/markdown-document/lib/markdown-document-view.coffee:140:7)
    at MarkdownDocumentView.module.exports.MarkdownDocumentView.refreshOutline (/home/<user>/.atom/packages/markdown-document/lib/markdown-document-view.coffee:194:6)
    at Object.module.exports.MarkdownDocument.refresh (/home/<user>/.atom/packages/markdown-document/lib/markdown-document.coffee:42:27)
    at atom-workspace.subscriptions.add.atom.commands.add.markdown-document:refresh (/home/<user>/.atom/packages/markdown-document/lib/markdown-document.coffee:25:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
  2x -1:39.4.0 editor:toggle-soft-wrap (div.markdown-preview.native-key-bindings)
     -1:26.5.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
     -1:18.8.0 markdown-preview-plus:sync-source (p.)
     -1:15.2.0 core:save-as (p.)
  2x -1:10.8.0 core:copy (p.)
  2x -1:01.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:58.2.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:56.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.7.0 markdown-document:toggle (atom-text-editor.editor.is-focused)
     -0:19.7.0 markdown-toc:toggle (div.markdown-preview.native-key-bindings)
     -0:00.4.0 markdown-document:refresh (div.markdown-preview.native-key-bindings)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
markdown-document, v0.1.1
markdown-preview-plus, v2.4.0
markdown-themeable-pdf, v1.0.2
markdown-toc, v0.4.1
markdown-writer, v2.3.5

# Dev
No dev packages
```

**Comment by kcyarn** [comment]
Try e56cb95

This will be the 0.2 release (I hope). The nav automatically updates as the document saves whether you choose to use the autosave feature or not. Killed the refresh button, but left the manual refresh command so it will look a little different. Non-sequential headers are whatever color your theme uses for caution.

**Comment by diqidoq** [comment]
Awesome. thx for chiming in! Greetings from Berlin, Germany!

**Comment by avonmoll** [comment]
I still get this when I'm working on a fresh document that has not been saved.

Can / should we be able to generate an outline for unsaved files?
