### ISSUE TITLE
Uncaught TypeError: Cannot read property '$apply' of undefined

### ISSUE THREAD

**Issue by maxjoehnk** [kcyarn/markdown-document#8]
1. Open a Markdown Document

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property '$apply' of undefined

```
At /Users/max/.atom/packages/markdown-document/lib/markdown-document-view.coffee:238

TypeError: Cannot read property '$apply' of undefined
    at MarkdownDocumentView.mdOutline (/Users/max/.atom/packages/markdown-document/lib/markdown-document-view.coffee:238:13)
    at /Users/max/.atom/packages/markdown-document/lib/markdown-document-view.coffee:84:9
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Commands

```
     -3:15.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:00.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:59.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:55.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:55.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:52.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:38.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:38.7.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -2:36.7.0 core:save (atom-text-editor.editor.is-focused)
  7x -2:19.2.0 markdown-preview:preview-file (atom-text-editor.editor)
  2x -1:02.4.0 markdown-document:toggle (atom-text-editor.editor.is-focused)
  2x -0:43.3.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
  5x -0:16.1.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:15 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:11.8.0 markdown-preview:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "haskell-ghc-mod",
      "haskell-pointfree",
      "ide-haskell",
      "autocomplete-haskell",
      "ide-haskell-cabal",
      "ide-haskell-repl",
      "language-haskell",
      "build-grunt",
      "grunt-runner",
      "browser-plus",
      "build",
      "build-gulp",
      "build-npm-apm"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.5
atom-beautify, v0.29.10
atom-material-syntax, v0.4.6
atom-material-ui, v1.3.3
atom-mocha, v0.0.6
atom-typescript, v10.1.5
bottom-dock, v0.4.4
busy, v0.6.0
docker, v0.7.0
file-icons, v1.7.17
flex-tool-bar, v0.10.2
gulp-manager, v0.2.19
highlight-selected, v0.11.2
jenkins, v0.3.5
linter, v1.11.14
linter-docker, v0.1.2
linter-eslint, v7.2.4
linter-jsonlint, v1.3.0
linter-manager, v0.2.12
linter-markdown, v1.5.2
linter-tslint, v0.10.0
markdown-document, v0.2.0
markdown-scroll-sync, v2.1.2
minimap, v4.24.7
minimap-bookmarks, v0.3.1
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
node-debugger, v1.7.0
project-manager, v2.9.7
rest-client, v1.2.0
terminal-plus, v0.14.5
todo-manager, v0.2.9
tool-bar, v1.0.0
tool-bar-main, v0.0.9
travis-ci-status, v1.1.1

# Dev
No dev packages
```

**Comment by kcyarn** [comment]
Do you experience the error when you don't use markdown-preview?

**Comment by case** [comment]
Fwiw I'm seeing this as well, when markdown-preview is enabled or disabled.
- Atom 1.10.2
- Mac OS 10.12

**Comment by MAWSpitau** [comment]
The same problem here :( I like the scrivener-idee and would like to use it - somehow.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.10
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '$apply' of undefined

```
At /home/marcel/.atom/packages/markdown-document/lib/markdown-document-view.coffee:300

TypeError: Cannot read property '$apply' of undefined
    at /home/marcel/.atom/packages/markdown-document/lib/markdown-document-view.coffee:300:21
```

### Commands

```
     -3:41.5.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
     -3:35.7.0 advanced-open-file:move-cursor-down (atom-text-editor.path-input.editor.mini.is-focused)
     -3:35.3.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
     -3:30.5.0 advanced-open-file:autocomplete (atom-text-editor.path-input.editor.mini.is-focused)
     -3:29.1.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
     -2:32.4.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
     -2:30.3.0 editor:consolidate-selections (atom-text-editor.path-input.editor.mini.is-focused)
     -2:30.3.0 core:cancel (atom-text-editor.path-input.editor.mini.is-focused)
     -1:03.8.0 markdown-document:toggle (atom-text-editor.editor.is-focused)
     -0:13.9.0 application:open-file (atom-text-editor.editor.is-focused)
     -0:12 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:08.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 application:open-folder (atom-text-editor.editor.is-focused)
     -0:04.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:close (div.package-detail.panels-item)
```

### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "language-gfm",
      "print-atom",
      "export-html",
      "minimap-bookmarks",
      "markdown-folder"
    ],
    "packagesWithKeymapsDisabled": [
      "spell-check"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v1.0.2 (active)
advanced-open-file, v0.16.4 (active)
atom-material-ui, v1.3.6 (active)
block-selection-mode, v0.3.0 (inactive)
export-html, v3.0.0 (inactive)
expose, v0.12.1 (inactive)
file-icons, v1.7.22 (active)
language-latex, v1.0.0 (active)
language-markdown, v0.17.0 (active)
m-a-w-syntax, v0.0.0 (inactive)
markdown-document, v0.2.0 (active)
markdown-folder, v0.5.0 (inactive)
markdown-scroll-sync, v2.1.2 (active)
markdown-table-formatter, v2.8.3 (active)
markdown-themeable-pdf, v1.2.0 (active)
markdown-writer, v2.6.1 (inactive)
minimal-syntax, v0.15.1 (inactive)
minimap, v4.25.5 (active)
minimap-autohide, v0.10.1 (active)
minimap-bookmarks, v0.4.2 (inactive)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-hide, v0.3.0 (active)
minimap-selection, v4.4.0 (active)
minimap-titles, v1.8.1 (inactive)
one-o-eight-syntax, v0.23.2 (inactive)
pdf-view, v0.50.0 (active)
project-manager, v3.2.5 (active)
seti-ui, v1.3.2 (inactive)
terminal-plus, v0.14.5 (active)
todo-show, v1.7.0 (inactive)
wordcount, v2.7.0 (active)
Zen, v0.16.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
